### ISSUE TITLE
Error on API route

### ISSUE THREAD

**Issue by Shomrat-Gil** [brickgale/laravue2-starter#1]
Hello,
I`m keep getting an error on API route before even accessing the controller.
The error is on 
"Illuminate\Filesystem" 
at the public function get($path, $lock = false) and its returning:
throw new FileNotFoundException("File does not exist at path {$path}"); on path "storage\framework\cache\..." this folder is empty.

Any idea or directions?
Thanks,
Gil

**Comment by brickgale** [comment]
Hi @Shomrat-Gil,

Do you mind sharing the code that caused the error? Or is the error occuring after installation?

**Comment by Shomrat-Gil** [comment]
Thanks for the reply,
This is its git:
https://github.com/Shomrat-Gil/laravel-spa
When debugging any route its going to Illuminate\Filesystem class and public function get($path, $lock = false)
looking for a files that do not exist through an exceptions and then entering the controller.

Thanks,

**Comment by Shomrat-Gil** [comment]
I think its related to jwt that using this path ' storage/framework/cache' to store the token time.
And since for some reason he cant find one the token return as pass and fail the call after login.
Any idea?
Thanks,

**Comment by brickgale** [comment]
I've noticed on your `routes/api.php` that you are using the default routing for laravel, maybe try using dingo for all api calls since I have already set it to use dingo and jwt-auth together. I'm not sure why you are getting error from `Illuminate\Filesystem` since at default I am not using `File` for any api calls out of the box.

**Comment by Shomrat-Gil** [comment]
Hi,
You are right - it's not with the app.
I wanted to remove the "dingo/api" layer.
I had the same with a fresh Laravel install with nothing add to it.
I think its related to the routes going through api.php because if I take the requests to the web.php all works fine.
Can`t figure why, but, its not with your code.
Thanks for the time !
